## Neural network
1. Input
2. Hidden Layers
3. Output

In [1]:
import torch
import torch.nn as nn

In [2]:
input_tensor = torch.tensor([
    [0.3471, 0.4547, -0.2356]
])

input_tensor

tensor([[ 0.3471,  0.4547, -0.2356]])

### Single layer NN

It is also called fully connceted

In [3]:
linear_layer = nn.Linear(
    in_features=3,
    out_features=2
)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [4]:
output = linear_layer(input_tensor)
output

tensor([[-0.7977,  0.6373]], grad_fn=<AddmmBackward0>)

In [5]:
# weights
linear_layer.weight

Parameter containing:
tensor([[-0.3218, -0.3911,  0.4376],
        [ 0.0473,  0.3179,  0.3077]], requires_grad=True)

In [6]:
# bias
linear_layer.bias

Parameter containing:
tensor([-0.4051,  0.5488], requires_grad=True)

### Multi layer network

In [7]:
model = nn.Sequential(
    nn.Linear(in_features=10, out_features=18),
    nn.Linear(in_features=18, out_features=20),
    nn.Linear(in_features=20, out_features=5)
)

In [8]:
input_tensor = torch.tensor([
    [-0.0014, 0.4038, 1.0305, 0.7521, 0.7489, -0.3968, 0.0113, -1.3844, 0.8705, -0.9743]
])

In [9]:
output_tensor = model(input_tensor)
output_tensor

tensor([[ 0.4464, -0.1006,  0.0700, -0.0440,  0.2319]],
       grad_fn=<AddmmBackward0>)