Tensors are a specialized data structure that's very similar to arrays and matrices.

In PyTorch, we use tensors to encode a model's inputs and outputs, as well as the model’s parameters.

Tensors are similar to NumPy arrays and ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory address with a capability called bridge-to-np-label, which eliminates the need to copy data. Tensors are also optimized for automatic differentiation (we'll see more about that later in the Autograd unit).

In [1]:
import torch
import numpy as np

## Initializing a tensor

### Directly from data
You can create tensors directly from data. The data type is automatically inferred.

In [2]:
data = [[1,2,3], [4,5,6]]
x_data = torch.tensor(data=data)
x_data

tensor([[1, 2, 3],
        [4, 5, 6]])

### From a NumPy array
Tensors can be created from NumPy arrays, and vice versa. Because numpy 'np_array' and tensor 'x_np' share the same memory location here, changing the value for one will change the other.

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

Numpy np_array value: 
 [[1 2 3]
 [4 5 6]] 

Tensor x_np value: 
 tensor([[1, 2, 3],
        [4, 5, 6]]) 



In [5]:
np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array after * 2 operation: 
 [[ 2  4  6]
 [ 8 10 12]] 

Tensor x_np value after modifying numpy array: 
 tensor([[ 2,  4,  6],
        [ 8, 10, 12]]) 



### From another tensor
The new tensor retains the properties (shape, data type) of the argument tensor, unless explicitly overridden.

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Random Tensor: 
 tensor([[0.3281, 0.5652, 0.0528],
        [0.7389, 0.6111, 0.8784]]) 



### With random or constant values
shape is defined by a tuple of tensor dimensions, which set the number of rows and columns in a tensor. In the functions below, shape determines the dimensionality of the output tensor.

In [9]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8754, 0.6792, 0.5622],
        [0.8970, 0.8944, 0.3448]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor attributes
Tensor attributes describe their shape, data type, and the device on which they're stored.

In [11]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on tensors
### Standard numpy-like indexing and slicing

In [12]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining tensors
You can use torch.cat to concatenate a sequence of tensors along a given dimension. torch.stack is a related tensor joining option that concatenates a sequence of tensors along a new dimension.

In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Arithmetic operations


In [16]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Single-element tensors
If you have a one-element tensor—for example, by aggregating all values of a tensor into one value— you can convert it to a Python numerical value using item()

In [18]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

12.0 <class 'float'>


### In-place operations
Operations that store the result into the operand are called in-place. They're denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

Note: In-place operations save some memory, but can be problematic when computing derivatives because of their immediate loss of history. Hence, we discourage using them in most situations.

In [20]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
