## PyTorch: A deep learning framework 

It is one of the morst popular deep learning framework

It is used in many published deep learning papers

Intitutive and user friendly.

In [4]:
import torch
import numpy as np

### Tensor:
1. Simmilar to array
2. Building block of neural network

In [3]:
lst = [[1,2,3], [4,5,6]]
t = torch.tensor(lst)
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
np_array = np.array(lst)
np_tensor = torch.from_numpy(np_array)
np_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
np_tensor.shape

torch.Size([2, 3])

In [8]:
np_tensor.dtype

torch.int64

In [9]:
np_tensor.device

device(type='cpu')

In [11]:
a = torch.tensor([[1, 1],
                  [2, 2]])

b = torch.tensor([[2, 2],
                  [3, 3]])

a+b

tensor([[3, 3],
        [5, 5]])

In [12]:
a*b

tensor([[2, 2],
        [6, 6]])